title: Daniel Ortega
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: light # Or use dark

# Profile information
name: Daniel Ortega
tagline: Software Engineer
about-description: >
  I am a Software Engineer motivated by challenges and quality software.
  I'm very interested in software development good practices, design and development of maintainable applications.
  I have experience in backend web applications and I'm recently studying to improve my frontend web skills.
  I like to work in Ruby, with Ruby on Rails framework, in Java with MVC frameworks and I enjoy agile methodologies.
pic: me.jpg # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: dorteganorambuena@gmail.com # Add your Email address
phone: +56984322835 # Add your Phone number
website: dortegan.github.io # Add your website, do not add http://
linkedin: daniel-antonio-ortega-norambuena-bb484b32 # Add your Linkedin handle
github: dortegan # Add your Github handle
twitter: '@D3ni3ls' # Add your Twitter handle

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
